"""
Django settings for daraja_project project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from a .env file placed next to manage.py (see .env.example).
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-mzyct-i16h3yq7m*0nju4)r-mzl@o(=73*f!-*4@w_a=7rrcn1",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "b2c",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "daraja_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "daraja_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Cache — used to store the short-lived Daraja OAuth access token so we don't
# request a new one on every API call. Swap for Redis/Memcached in production
# by changing BACKEND/LOCATION only; the rest of the code is unaffected.
# ---------------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "daraja-b2c-cache",
    }
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# ---------------------------------------------------------------------------
# Safaricom Daraja API configuration
# All values are read from environment variables — see .env.example.
# Get consumer key/secret and shortcodes from https://developer.safaricom.co.ke
# ---------------------------------------------------------------------------
DARAJA_ENV = os.getenv("DARAJA_ENV", "sandbox")  # "sandbox" or "production"

DARAJA_BASE_URL = (
    "https://api.safaricom.co.ke"
    if DARAJA_ENV == "production"
    else "https://sandbox.safaricom.co.ke"
)

DARAJA_CONSUMER_KEY = os.getenv("DARAJA_CONSUMER_KEY", "")
DARAJA_CONSUMER_SECRET = os.getenv("DARAJA_CONSUMER_SECRET", "")

# The Org shortcode / Paybill that money is disbursed FROM.
DARAJA_INITIATOR_SHORTCODE = os.getenv("DARAJA_INITIATOR_SHORTCODE", "")
# Name of the API operator configured on the Daraja portal for this shortcode.
DARAJA_INITIATOR_NAME = os.getenv("DARAJA_INITIATOR_NAME", "")
# Plaintext initiator password (used only to derive DARAJA_SECURITY_CREDENTIAL
# at request time — never sent to Safaricom in plaintext, never logged).
DARAJA_INITIATOR_PASSWORD = os.getenv("DARAJA_INITIATOR_PASSWORD", "")

# Path to Safaricom's public certificate (.cer) used to RSA-encrypt the
# initiator password into the SecurityCredential. Sandbox and production use
# different certificates — see README for where to download each.
DARAJA_CERTIFICATE_PATH = os.getenv(
    "DARAJA_CERTIFICATE_PATH", str(BASE_DIR / "certs" / "SandboxCertificate.cer")
)

# One of: SalaryPayment, BusinessPayment, PromotionPayment
DARAJA_B2C_COMMAND_ID = os.getenv("DARAJA_B2C_COMMAND_ID", "BusinessPayment")

# Publicly reachable HTTPS URLs Safaricom will POST results/timeouts to.
# During local development, expose your dev server with a tool like ngrok
# and point these at the ngrok URL (see README).
DARAJA_B2C_RESULT_URL = os.getenv(
    "DARAJA_B2C_RESULT_URL", "https://example.com/api/b2c/callback/result/"
)
DARAJA_B2C_TIMEOUT_URL = os.getenv(
    "DARAJA_B2C_TIMEOUT_URL", "https://example.com/api/b2c/callback/timeout/"
)

# Optional: restrict initiate endpoint with a shared secret header instead of
# full auth, useful for server-to-server calls from an internal system.
DARAJA_API_SHARED_SECRET = os.getenv("DARAJA_API_SHARED_SECRET", "")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "b2c": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
    },
}
