# Generated by Django 5.2.17 on 2026-09-20 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="B2CTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Normalized MSISDN, e.g. 254712345678", max_length=15
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("remarks", models.CharField(blank=True, max_length=100)),
                ("occasion", models.CharField(blank=True, max_length=100)),
                ("command_id", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted by Safaricom"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timed out"),
                            ("REJECTED", "Rejected by Safaricom"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "originator_conversation_id",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "conversation_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("response_code", models.CharField(blank=True, max_length=10)),
                ("response_description", models.CharField(blank=True, max_length=255)),
                ("result_code", models.CharField(blank=True, max_length=10)),
                ("result_desc", models.CharField(blank=True, max_length=255)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Safaricom M-Pesa receipt number",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "transaction_completed_at",
                    models.CharField(blank=True, max_length=50),
                ),
                ("receiver_public_name", models.CharField(blank=True, max_length=255)),
                ("raw_initiate_response", models.JSONField(blank=True, null=True)),
                ("raw_callback", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
